---

  - name: Install ddclient with Apt
    apt:
      name: ddclient
    become: yes

  - name: remove apt default ddclient config
    file:
      path: /etc/ddclient.conf
      state: absent
    become: yes

  - name: Push out ddclient binary
    copy:
      src: ddclient
      dest: /sbin/ddclient
      owner: root
      group: root
      mode: 0755
    become: yes

  - name: Push out ddclient defaults
    copy:
      src: ddclient.defaults
      dest: /etc/default/ddclient
      owner: root
      group: root
      mode: 0600
    become: yes

  - name: DDClient etc directory
    file:
      path: /etc/ddclient
      owner: root
      group: root
      mode: 0600
      state: directory
    become: yes

  - name: Push out ddclient config
    template:
      src: ddclient.conf.j2
      dest: /etc/ddclient/ddclient.conf
      owner: root
      group: root
      mode: 0600
    become: yes

  - name: Register and start ddclient
    service:
      name: ddclient
      state: restarted
      enabled: yes
    become: yes
