---
  - name: Update Pi password
    user:
            name: pi
            state: present
            password: "{{ ssh_password }}"
    become: yes

  - name: remove alex
    user:
            name: alex
            state: absent
    become: yes

  - name: Passwordless sudo for photos
    lineinfile:
            line: '%sudo   ALL=(ALL:ALL) NOPASSWD:ALL'
            state: present
            regexp: '^%sudo'
            path: /etc/sudoers
            validate: 'visudo -cf %s'
    become: yes

  - name: Fix SSH
    lineinfile:
      line: 'IPQoS cs0 cs0'
      state: present
      regexp: 'IPQoS cs0 cs0'
      path: /etc/ssh/sshd_config
      insertafter: EOF
    become: yes
    notify:
      - Restart sshd

  - name: Set boot behaviour
    shell: "sudo raspi-config nonint do_boot_behaviour B2"

  - name: Fix photos archive perms
    file:
            path: /home/pi/icloud_photos
            state: directory
            owner: pi
            group: pi
            mode: u=rwX,g=r,o=r
            recurse: yes

  - name: Install X via Apt
    apt:
            name: "{{ item }}"
            state: present
    loop:
            - libexif12
            - qt5-default
            - xinit
    become: yes

  - name: Get Slide software
    unarchive:
            creates: slide_0.9.5/slide
            dest: /home/pi
            owner: pi
            group: pi
            remote_src: yes
            src: https://github.com/NautiluX/slide/releases/download/v0.9.5/slide_rpi_0.9.5.tar.gz

  - name: Make executable
    file:
            path: /home/pi/slide_0.9.5/slide
            mode: 0700
    become: yes

  - name: Update XWrapper to allow anybody
    lineinfile:
            path: /etc/X11/Xwrapper.config
            state: present
            regexp: '^allowed_users='
            line: allowed_users=anybody
    become: yes

  - name: Add startx to bashrc
    lineinfile:
            path: /home/pi/.bashrc
            state: present
            regexp: 'startx'
            line: '[ ! -n "${SSH_CONNECTION}"  ] && startx'
            insertafter: EOF

  - name: Create .xinitrc file
    copy: 
            src: xinitrc
            dest: /home/pi/.xinitrc
            owner: pi
            group: pi
            mode: 0600

  - name: Nightly reboot cron
    cron: 
      name: "Night reboot"
      minute: "0"
      hour: "4"
      job: "sudo reboot"

  - name: Wireless power management cron
    cron: 
      name: "wlconfig"
      special_time: reboot
      state: present
      job: "sudo iwconfig wlan0 power off"

