---
  - name: Install netatalk for TimeMachine
    apt:
      name: netatalk
      state: present
    become: yes

  - name: Install netatalk config file
    copy:
      src: afp.conf
      dest: /etc/netatalk/afp.conf
      owner: root
      group: root
      mode: 0600
    become: yes
    notify:
      - Restart netatalk

  - name: Register and start netatalk
    service:
      name: netatalk
      state: started
      enabled: yes
    become: yes
  
