---
  - name: install dependencies
    become: "{{ ansible_distribution != 'MacOSX' }}"
    package:
      name:
        - git
        - zsh
      state: present

  - name: clone oh-my-zsh for users
    tags:
     # Suppress warning: [ANSIBLE0006] git used in place of git module
      # Git module doesn't allow us to set `core.autocrlf=input`.
      - skip_ansible_lint
    become: yes
    become_user: alex
    # core.autocrlf=input prevents https://github.com/robbyrussell/oh-my-zsh/issues/4402
    command: 'git clone -c core.autocrlf=input --depth=1 https://github.com/robbyrussell/oh-my-zsh.git .oh-my-zsh'
    args:
      chdir: /home/alex
      creates: '/home/alex/.oh-my-zsh'

  - name: Install My ZSH theme
    copy: 
      src: mytheme.zsh-theme
      dest: /home/alex/.oh-my-zsh/custom/themes/mytheme.zsh-theme
      owner: alex
      group: alex
      mode: 0600

  - name: Get Starship installer
    get_url:
      url: https://starship.rs/install.sh
      dest: /tmp/starship_install.sh
      mode: 0700
      owner: root
      group: root

  - name: Install starship
    command: /tmp/starship_install.sh -f
    args:
      creates: /usr/local/bin/starship
    become: yes

  - name: Install starship toml config file
    copy: 
      src: starship.toml
      dest: /home/alex/.starship.toml
      owner: alex
      group: alex
      mode: 0600

  - name: Install starship toml config file
    copy: 
      src: starship.toml
      dest: /home/alex/.starship.toml
      owner: alex
      group: alex
      mode: 0600

  - name: Update alex password
    user:
      name: alex
      state: present
      password: "{{ ssh_password }}"
      shell: /usr/bin/zsh
    become: yes

  - name: Setup SSH dir for alex
    file:
      path: "/home/{{ item }}/.ssh"
      state: directory
      owner: "{{ item }}"
      group: "{{ item }}"
      mode: 0700
    loop:
      - alex

  - name: Push out SSH keys for alex
    copy:
            src: authorized_keys
            dest: "/home/{{ item }}/.ssh/authorized_keys"
            owner: "{{ item }}"
    loop:
      - alex

  - name: Get shell defaults
    copy:
      src: shellrc
      dest: /home/alex/.shellrc
      owner: alex
      group: alex

  - name: Get shell defaults
    copy:
      src: zshrc
      dest: /home/alex/.zshrc
      owner: alex
