---

 - include: setup.yml
 - include: alex.yml
   when: '"general" in group_names'
 - include: ubuntu.yml
   when: ansible_facts['os_family'] == "Debian"
 - include: upgrade.yml
   when: ansible_facts['os_family'] == "Debian"

 - name: Check if we need to reboot
   stat: 
     path: /var/run/reboot-required
   register: reboot_required 

 - name: Reboot if needed after update
   reboot:
     connect_timeout: 300
     post_reboot_delay: 180
   tags: reboot
   become: yes
   when: ansible_facts['os_family'] == "Debian" and reboot_required.stat.exists == True
