---
  - name: Disable IPv6 on Ubuntu - install rc.local
    copy: 
      src: rc.local
      dest: /etc/rc.local
      owner: root
      group: root
      mode: 0755
    become: yes

  - name: Disable IPv6 on Ubuntu - install sysctls
    blockinfile:
        path: /etc/sysctl.conf
        insertafter: EOF
        block: |
            ### Added to disable IPv6
            net.ipv6.conf.all.disable_ipv6 = 1
            net.ipv6.conf.default.disable_ipv6 = 1
            net.ipv6.conf.lo.disable_ipv6 = 1
    become: yes
         
