---

  - import_tasks: zfs.yml

  - name: Install apt-transport-https
    apt:
      name: apt-transport-https
      state: present
    become: yes

  - name: Install OpenCL hardware transcoding library
    apt:
      name: ocl-icd-libopencl1
      state: present
    become: yes

  - name: Add Plex apt key (Ubuntu & Debian with systemd)
    apt_key:
      url: https://downloads.plex.tv/plex-keys/PlexSign.key
      state: present
    become: yes

  - name: Add Plex apt repo (Ubuntu & Debian with systemd)
    apt_repository:
      repo: deb https://downloads.plex.tv/repo/deb public main
      state: present
    changed_when: false
    become: yes

  - name: Apt install Plex
    apt:
      name: plexmediaserver
      state: present
      update_cache: true
    notify: restart plex
    become: yes

  - name: Install default preferences file
    copy:
      src: Preferences.xml
      dest: "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Preferences.xml"
      owner: plex
      group: plex
      mode: 0600
    become: yes

  - name: Autostart Plex and start service
    service:
      name: plexmediaserver
      enabled: true
    notify: restart plex
    become: yes
