---
  - name: Photo Syncer Cron
    cron:
      hour: 2
      minute: 0
      job: "chronic /home/alex/scripts/photo_syncher.sh"
      name: "Photo Syncer Cron"
      state: absent


  - name: Push out script
    file:
      src: photo_syncer.yml
      dest: ~/scripts/photo_syncher.sh
      owner: alex
      group: alex
      mode: 0700